### ISSUE TITLE
レビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [ryusei-tadokoro/today_fashion#148]
レビュー依頼ありがとうございます。
アプリ拝見しました。一定水準以上に達していると判断しました。LGTMです。
以後、週次報告等は行わなくて大丈夫です。
以下、就活の準備と並行して取り組みましょう！

---

- README.mdを就活向けのアピール要素の高いものに編集
- ファビコン対応
- ユーザー登録画面の背景（ファースト画面と同じような世界観が望ましいかと）
- testフォルダの削除
- テストコード拡充（RSpec）
- 使用していないファイルの削除（xxx_helper.rb）
- ヘッダーにあるGitHubへの動線を削除（コードが公開されているとユーザーに思われると不安を与えてしまう恐れがあるため）

**Comment by ryusei-tadokoro** [comment]
- [ ] README.mdを就活向けのアピール要素の高いものに編集
- [x] ファビコン対応
- [x] ユーザー登録画面の背景（ファースト画面と同じような世界観が望ましいかと）
- [x] testフォルダの削除
- [ ] テストコード拡充（RSpec）
- [x] 使用していないファイルの削除（xxx_helper.rb）
- [x] ヘッダーにあるGitHubへの動線を削除（コードが公開されているとユーザーに思われると不安を与えてしまう恐れがあるため）
