### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by kenchasonakai** [ryusei-tadokoro/today_fashion#83]
MVPリリースおめでとうございます！
このissueに返答する形で本リリース予定日の返答をお願いいたします
以下にレビュー内容を記載します

## UI面
フォームやボタンにデザインが当たっていなかったのでCSSフレームワークを使っていたらさっと当ててしまうと良いかと思います
画像未登録時に鳥の画像が出てくるのが何か意味があるのか気になりました
服装指数が何を指しているのかわかりにくかったです
服の登録の項目が多いので入力方法を工夫するなどしてあげると良いかと思います。ステップフォームなどがあると技術的にアピールできるポイントにもなるかと思います。
Topページについている都道府県検索機能は服装指数が見れるようにして、別で天気予報ページを作ると機能間のイメージのギャップが少なくなるかなと思いました

## セキュリティ面
URLを直接入力すると他の人の服データを操作できてしまうので修正しましょう

## 技術面
READMEに書いてあるCI/CDの導入やDockerを使った開発環境の構築、天気や服装指数のSNS共有とOGPの設定などを行うと技術的にアピールできるポイントが増やせそうです

**Comment by ryusei-tadokoro** [comment]
レビューありがとうございます！
また、返信遅れてしまい申し訳ありません。
いただいたコメントを参考にissueを作成していきたいと思います。

**Comment by ryusei-tadokoro** [comment]
すみません、本リリース日は4/8(月)とさせてください。
よろしくお願いいたします。
